### PR TITLE
fix always on display

### PR DESCRIPTION
**Pull request by Drhaal**
Seems to work on android Q with lineage os 17.1 . 
Not tested on other devices.

### CODE REVIEW

**Comment by enricocid** [comment]
Thanks! Could You please add (and test) this?

```
if (VersioningHelper.isQ()) putLong(MediaMetadataCompat.METADATA_KEY_DURATION, currentSong.first?.duration!!)
            putString(MediaMetadataCompat.METADATA_KEY_ARTIST, currentSong.first?.artist)
            putString(MediaMetadataCompat.METADATA_KEY_AUTHOR, currentSong.first?.artist)
            putString(MediaMetadataCompat.METADATA_KEY_COMPOSER, currentSong.first?.artist)
            putString(MediaMetadataCompat.METADATA_KEY_TITLE, currentSong.first?.title)
            putString(MediaMetadataCompat.METADATA_KEY_DISPLAY_TITLE, currentSong.first?.title)
            putString(MediaMetadataCompat.METADATA_KEY_ALBUM_ARTIST, currentSong.first?.album)
            putString(MediaMetadataCompat.METADATA_KEY_DISPLAY_SUBTITLE, currentSong.first?.album)
            putString(MediaMetadataCompat.METADATA_KEY_ALBUM, currentSong.first?.album)
            BitmapFactory.decodeResource(playerService.resources, R.drawable.ic_music_note)?.let { bmp ->
                putBitmap(MediaMetadataCompat.METADATA_KEY_DISPLAY_ICON, bmp)
            }
```

Just to be sure to support different implementations. Also, could You please post a debug apk here so I can try it on 3rd party AOD/some ROM?
Thanks.

**Comment by Drhaal** [comment]
Done,
Everything seems to work as before on my device.
I added the APK at the root of the project (I dont know if there is other ways to send it).

**Comment by enricocid** [comment]
No no, don't add APK to the root of the project, just share it with gdrive or similar in the comments 😉

**Comment by Drhaal** [comment]
Ok here's the link to dowload the APK
https://send.firefox.com/download/2529cd5b94ac88ae/#j5jDY-2_GxqUgQEV7xtWxQ

**Comment by enricocid** [comment]
Thanks, gonna release a new version this weekend 😉

**Pull request merged**
