### PR TITLE
Make the app respond to media button action intents

### PR DESCRIPTION
**Pull request by gaycodegal**
This successfully makes the app respond to intents launched from other applications. I tested this with my AI and it worked, but I'm not an expert in this domain so I can't say my solution is the "Best" solution but it definitely works.

Its possible there's something to be done with 

```
session.setFlags(
        MediaSessionCompat.FLAG_HANDLES_MEDIA_BUTTONS or
        MediaSessionCompat.FLAG_HANDLES_TRANSPORT_CONTROLS
)
```

as suggested here https://developer.android.com/guide/topics/media-apps/interacting-with-assistant but again my code works so good enough for me.

Note that this is not full AI support as I did not implement `ACTION_PLAY_FROM_SEARCH`, I only implemented stop, play, prev, next, toggle

### CODE REVIEW

**Comment by gaycodegal** [comment]
this PR implements the feature request https://github.com/enricocid/Music-Player-GO/issues/331

**Comment by gaycodegal** [comment]
oh also it should be noted this is not necessarily the correct place for this code to go within your app's architecture, I just put it here and it worked so I submitted this PR. I do see you have a MediaBtnReceiver that like 'should' be doing what my PR does but i was never able to trigger this code path, which is why i just put my thing in

**Comment by enricocid** [comment]
Thank You. I will test it asap! :)

**Comment by gaycodegal** [comment]
I was doing further tests and found i should have been using isPlaying instead of attempting to check the state constants directly. checking directly leads to a bug where doing play then pause ignores the pause request because resumed != playing

**Comment by gaycodegal** [comment]
ok bug fixed, all good now

**Comment by gaycodegal** [comment]
oh also looking like i might need to set a resultCode from this method to tell people we did something about it, will try to get to that tomorrow

**Comment by gaycodegal** [comment]
ok tested this, i can detect the OK in the AI app, PR now good for your review

**Comment by enricocid** [comment]
Thank You 😆

**Comment by enricocid** [comment]
@gaycodegal what is AI app? 😃
How am I supposed to reproduce what "AI app" does?

I'm testing the debug APK and works good with my headsets.

**Comment by gaycodegal** [comment]
I'll include a code snippet of sending an intent to your app soonish, work is busy this week so no time for fun. AI app will be published in full open source as soon as I get it not using maven dependency i do not trust which may take a little while

**Comment by enricocid** [comment]
Super!

**Comment by enricocid** [comment]
Hi, I have tested using the media controller test

https://developer.android.com/guide/topics/media-apps/audio-app/media-controller-test

Merging :)

**Comment by gaycodegal** [comment]
Sorry for delays, work was busy. But good to know a test app exists!

**Pull request merged**
