### PR TITLE
create separates button to save player position and mark song as loved

### PR DESCRIPTION
**Pull request by Drhaal**
Hi, 
I modified #207 to fit with the new version of the app.

Currently The buttons to save the player position and to mark the song as loved are both a the left of the the precise volume control. 
This kinda make the interface bloated so if you have an idea on how to improve this i can make the changes

### CODE REVIEW

**Comment by enricocid** [comment]
I'd probably opt for one button and a popup menu with two options to show on click. 
Like this one:
https://github.com/enricocid/Music-Player-GO/blob/4e70d9122c0d43d9886d7835c72efcc8985310a8/project/app/src/main/java/com/iven/musicplayergo/helpers/DialogHelper.kt#L234
:)

**Comment by Drhaal** [comment]
I implemented this but the result in not really ergonomic.
Maybe I can replace the equalizer button with the one to save the player position. And put the equalizer in the option ? Like in the old version

**Comment by enricocid** [comment]
> I implemented this but the result in not really ergonomic.
> Maybe I can replace the equalizer button with the one to save the player position. And put the equalizer in the option ? Like in the old version

I don't know ... I have to think about that one :)

**Comment by RickyM7** [comment]
@Drhaal @enricocid Would it be possible to build a debug version of this PR? I would like to test it. I don't know if there is an option to build a debug version, but if a small change is made in the PR the debug version will be build automatically, I think.

**Comment by Drhaal** [comment]
I don't know if automatic building is possible without a CI pipeline.
I will build a debug apk tomorrow if I can and publish it here. But this PR is currently in a janky state for ergonomy.

@enricocid I think we could keep separate button for saving time and marking song as loved by replacing the equilizer button by a pop-up button. A + icon wich would make apear a small pop up with the icon for equilizer and saving time. I think a can make a similiar popup to the one used for app shurtcuts on some android launcher but with only the icons.

**Comment by enricocid** [comment]
> I don't know if automatic building is possible without a CI pipeline.
> I will build a debug apk tomorrow if I can and publish it here. But this PR is currently in a janky state for ergonomy.
> 
> @enricocid I think we could keep separate button for saving time and marking song as loved by replacing the equilizer button by a pop-up button. A + icon wich would make apear a small pop up with the icon for equilizer and saving time. I think a can make a similiar popup to the one used for app shurtcuts on some android launcher but with only the icons.

Agree 👍🏻 

@RickyM7 unfortunately I'm not able to build an apk for now :)

**Comment by RickyM7** [comment]
@enricocid No problem, when it's possible, if you want I can test it on my phone.

**Comment by Drhaal** [comment]
Here's a link to the debug apk.
https://framadrop.org/lufi/r/_B6e_oj5sR#dk0zLYxZqEMS/P9W/iIdE6/UeBoEZZQpskoyyZefQzE=

As stated it's still in development so it's not really user friendly.
The current problem is that currently when a song is marked the love button can only de-mark it and not save the time anymore.
So i will keep separate buttons for saving time/ marking as loved and hide the save time one under a pop-up.

**Comment by RickyM7** [comment]
@Drhaal Corrupted Apk.Apk corrupted, I could not install.

**Comment by Drhaal** [comment]
https://framadrop.org/lufi/r/5FjhvvxBZ8#KPVxW/fg/ncd62Q9QjnhlxE/hoOI3ireTRM/T7xyB9I=
This one seems to work for me

**Comment by RickyM7** [comment]
In my tests I found only two problems:
1. This button does not work.
button
2. Apparently a bug occurred with the string of that part.
string

My idea about this feature: I think just a button to save the position in the player and mark as loved is enough. My idea would be that by just clicking the button only once the song would be marked as loved and by pressing and holding the button the position would be saved, and to remove a song as loved you should click the button once, if you pressed and held the button on a song marked as loved it would save/re-save the position in the player.

**Comment by Drhaal** [comment]
The bugs are normal singe this PR is in a developpement state.

I already thought about a long press to save the time but I think it's hard for a user to discover this feature. There's no visual clue to indicate that you can long press this button so lot of users might think the options to save time was removed or just never existed.
If you have an idea on how to make the long press easily discoverable by users I think it could be a better solution than a pop-up.

**Comment by RickyM7** [comment]
@Drhaal Many apps use tips to explain certain features, what do you think of doing this here as well. For example, when opening the song progress part for the first time (where is the button to mark as loved, precise control of the volume, etc.) or by first clicking the button to mark a song as loved the tip would appear.

Example:
tips

**Comment by Drhaal** [comment]
Here's an updated version using a pop-up to save the player position.
https://framadrop.org/lufi/r/m7kFd1_0aB#1hYxs8V94sI8JRE/JuNaurlQfdZi60zCDEvDnn2foAQ=

I don't about the explicative pop-up. Personally I don't like them since I think they are easy to forget once seen and I prefer to have all actions bound to a visible icon. @enricocid any preference for this ?

**Comment by RickyM7** [comment]
@Drhaal I really liked the menu, it was really nice in my opinion. The best of this menu is the possibility to add other extra options (such as the "sleep timer" for example) without changing the UI completely.

**Comment by RickyM7** [comment]
> @RickyM7 about ui tips: I don't want to make the app complex and add new third party components :)

That's great, the simplicity of the MPGO is one of its positives.

**Comment by Drhaal** [comment]
Okay I just updated the MR with the "final" version let me know what you think about it.

I just noticed you added a CI pipeline to the app so the apk is available on its last automatic build (thanks for this it will realy make future PR testing easier)

**Comment by enricocid** [comment]
> Okay I just updated the MR with the "final" version let me know what you think about it.
> 
> I just noticed you added a CI pipeline to the app so the apk is available on its last automatic build (thanks for this it will realy make future PR testing easier)

Thanks gonna test tomorrow :) 


@RickyM7 Thanks, I'm going to try tomorrow and let you know :)

**Comment by enricocid** [comment]
Merging ... thanks :)
I'm going to review it a little ... like moving the button on the right, use overflow, and a little review of the popup :) Thanks

**Pull request merged**
