### PR TITLE
fixed blinking cursor

### PR DESCRIPTION
**Pull request by bullheadandplato**
[See](https://github.com/enricocid/Music-Player-GO/issues/104#issuecomment-573447828)

### CODE REVIEW

**Comment by enricocid** [comment]
Thanks :)

**Comment by enricocid** [comment]
Hello, I unfortunately had to revert as I'm experiencing styling issues. The problem is that we can't apply a dialog theme. The theme must extend a preference theme.
If the problem is the theme then we could try to set a custom theme to the dialogs title?

**Comment by bullheadandplato** [comment]
```
<style name="BaseTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        .....
        <item name="preferenceTheme">@style/PrefTheme</item>
    </style>

    <style name="PrefTheme" parent="PreferenceThemeOverlay">
        <item name="android:scrollbars">none</item>
    </style>
```

**Comment by bullheadandplato** [comment]
As it turns out that blinking thing is not cursor but actually is scrollbar. so setting above will fix it. Can you try that?

**Comment by enricocid** [comment]
Works great now! You can send me a PR if You want. Thanks!

**Comment by bullheadandplato** [comment]
#121

**Pull request merged**
