### PR TITLE
Update and rename project/app/src/main/res/values/strings.xml to proj…

### PR DESCRIPTION
**Pull request by z1q7p3m9**
…e/uygulama/src/ana/res/değerler/KURDISH.strings.xml

Hello, I live in Turkey, but I'm not Turkish. I know Kurdish and I love the program. I translated into Kurdish. I would like you to publish. I'll be glad if you come back to me. I love you.

### CODE REVIEW

**Comment by enricocid** [comment]
I would be happy to add Kurdish😎
Anyway the pull request is a little bit messed up so I can't merge.

If you want you can use weblate to add Kurdish. It is easier. You find the link on the homepage.

Alternatively You can wait for me to merge these changes manually 👍🏻😉

**Comment by z1q7p3m9** [comment]
> Kürtçe eklemekten mutluluk duyarım😎
> Her neyse, çekme isteği biraz karışık, bu yüzden şimdilik birleştiremiyorum.
> 
> Dilerseniz weblate'i Kürtçe eklemek için kullanabilirsiniz. Daha kolay. Bağlantıyı ana sayfada bulabilirsiniz.
> 
> Alternatif olarak, bu değişiklikleri manuel olarak birleştirmemi bekleyebilirsiniz 👍🏻😉

Hello buddy. I just met the application. After doing some research, I saw that it has a "translation" feature. I would love to see a program written in my native language here. You said I can add the Kurdish language, I am very glad. You answered very quickly. Congratulations.

**Comment by enricocid** [comment]
> > Kürtçe eklemekten mutluluk duyarım😎
> > Her neyse, çekme isteği biraz karışık, bu yüzden şimdilik birleştiremiyorum.
> > Dilerseniz weblate'i Kürtçe eklemek için kullanabilirsiniz. Daha kolay. Bağlantıyı ana sayfada bulabilirsiniz.
> > Alternatif olarak, bu değişiklikleri manuel olarak birleştirmemi bekleyebilirsiniz 👍🏻😉
> 
> Hello buddy. I just met the application. After doing some research, I saw that it has a "translation" feature. I would love to see a program written in my native language here. You said I can add the Kurdish language, I am very glad. You answered very quickly. Congratulations.

Absolutely. You are allowed to add translations.
Anyway, Your PR is wrong for these reasons:

1) You shouldn't rename the folders structure :)
2)You  shouldn't delete /values/strings :)

To add Kurdish You have to add translated strings.xml file inside a folder called "values-ku".

So prepare another pull request and I will merge it :)

**Comment by enricocid** [comment]
Hi, I've added Kurdish translations based on this pr.

Anyway there are some missing strings 👍🏻 

You can fork the project and add the translated in values-ku/strings.xml, at the end of everything

PS You only need to translate the highlighted content (**):

`<string name="open_git_pref_title">**GitHub page**</string>`

Here are the missing strings:

```
    <string name="repeat_loop_enabled">Dubare &#8734; enabled!</string>
    <string name="open_git_pref_title">GitHub page</string>
    <string name="open_git_pref_summary">Open the project\'s page for more info :)</string>
    <string name="faq_summary">FAQ and supported media formats :P</string>
    <string name="found_songs_pref_title">Found songs: %1d</string>
    <string name="accent_pref_title">Accent</string>
    <string name="active_fragments_pref_title">Active tabs</string>
    <string name="active_fragments_pref_warning">You can\'t just remove all the tabs! :P</string>
    <string name="precise_volume_pref_title">Precise volume control</string>
    <string name="precise_volume_pref_summary_on">Disable precise volume control</string>
    <string name="precise_volume_pref_summary_off">Enable precise volume control</string>
    <string name="focus_pref_title">Audio focus</string>
    <string name="focus_pref_summary_on">Disable audio focus management</string>
    <string name="focus_pref_summary_off">Enable audio focus management</string>
    <string name="headset_pref_title">Headset plug</string>
    <string name="headset_pref_summary_on">Disable headset plug management</string>
    <string name="headset_pref_summary_off">Enable headset plug management</string>
    <string name="filter_pref_title">Filters</string>
    <string name="covers_pref_title">Embedded album\'s covers</string>
    <string name="covers_pref_summary_on">Show embedded album\'s covers</string>
    <string name="covers_pref_summary_off">Don\'t show embedded album\'s covers</string>
    <string name="loved_songs_save_time">Save song position</string>
    <string name="equalizer">Equalizer</string>
    <string name="equalizer_bb">Bass boost</string>
    <string name="equalizer_v">Surround audio</string>
    <string name="error_list_ended">List ended.</string>
    <string name="error_eq">Ooops, an error occurred!</string>
    <string name="on_list_ended_pref_title">When a list ends &#8230;</string>
    <string name="on_list_ended_pref_stop_title">Stop</string>
    <string name="on_list_ended_pref_continue_title">Continue</string>
    <string name="song_visual_pref_title">Song visualization</string>
    <string name="song_visual_pref_tl_title">Title</string>
    <string name="song_visual_pref_fn_title">Filename</string>
    <string name="eq_pref_note_summary">Note: The system equalizer will be preferred unless you turn off the app \"system equalizer\" from the system settings. :)</string>
    <string name="fast_seeking_pref_title">Fast seeking</string>
    <string name="fast_seeking_pref_summary">Fast forward/rewind step (seconds)</string>
    <string name="fast_seeking_actions_pref_title">Additional notification actions</string>
    <string name="fast_seeking_actions_pref_summary_off">Prefer close/repeat actions</string>
    <string name="fast_seeking_actions_pref_summary_on">Prefer fast seeking actions</string>
```

**Pull request closed without merging**
