### PR TITLE
Update Indonesian translation

### PR DESCRIPTION
**Pull request by zmni**

### CODE REVIEW

**Comment by enricocid** [comment]
Thanks. I'm working on some features and already committed some changes and new strings (some strings got deleted) so can't accept this one.
I'm gonna comment here once finished so you can update strings :) thanks

**Comment by enricocid** [comment]
Hello,

These are the final strings for 4.0.0 update.

https://drive.google.com/open?id=1Q0SorF76nE6Yqq3nLMVoJMdGvidrONTP

Send me translated strings here, don't open a pull request, I'm gonna include them in 4.0.0 giving You proper credits.
Thanks. :)

**Comment by zmni** [comment]
It's done. [strings.xml.zip](https://github.com/enricocid/Music-Player-GO/files/3916255/strings.xml.zip)

**Comment by enricocid** [comment]
Thanks! :)

**Comment by enricocid** [comment]
Hello and sorry for disturb, but I added few strings. Could You translate them?
Thanks again.


```   
<string name="supported_formats_title">Supported media formats</string>

<string name="supported_formats_summary">Open this page if You are experiencing any issue related to supported media formats :P</string>

<string name="supportedFormats"><![CDATA[
    Music Player GO implements native <a href="https://developer.android.com/guide/topics/media/mediaplayer">MediaPlayer API</a>,
    that supports the following <a href="https://developer.android.com/guide/topics/media/media-formats">media formats</a>.<br/><br/>
    Instructions to get certain codecs working:<br/>
    Opus, for example, is supported natively since Android 5.0, but only in the Matroska (.mkv) container. Opus file type/container is not detected
    and not supported by MediaPlayer API. A simple workaround to detect and play Opus encoded files is to replace
    their extension (.opus) with the supported container (.mkv).<br/>
    Check the "Supported File Type(s) / Container Formats" from the
    <a href="https://developer.android.com/guide/topics/media/media-formats">supported media formats</a> page to know the supported container given the format/codec.<br/><br/>
    <i><font color="#F38596">Thanks for using Music Player GO ♥</font></i>
  ]]>
</string>
```

**Comment by zmni** [comment]
```xml
<string name="supported_formats_title">Format media yang didukung</string>

<string name="supported_formats_summary">Buka halaman ini jika anda mengalami masalah terkait dengan format media yang didukung :P</string>

<string name="supportedFormats"><![CDATA[
    Music Player GO mengimplementasikan <a href="https://developer.android.com/guide/topics/media/mediaplayer">API MediaPlayer</a> bawaan android,
    yang mendukung banyak <a href="https://developer.android.com/guide/topics/media/media-formats">format media</a>.<br/><br/>
    Instruksi untuk membuat codec tertentu berfungsi dengan baik:<br/>
    Sebagai contoh, Opus, didukung secara bawaan sejak Android 5.0, tetapi hanya dalam kontainer Matroska (.mkv). Kontainer/tipe berkas Opus tidak bisa dideteksi
    dan tidak didukung oleh API MediaPlayer. Solusi sederhana untuk mendeteksi dan memutar berkas Opus adalah dengan mengganti
    ekstensinya (.opus) dengan ekstensi yang didukung (.mkv).<br/>
    Lihat tabel "Format Kontainer / Tipe Berkas yang Didukung" di halaman pengembang android tentang
    <a href="https://developer.android.com/guide/topics/media/media-formats">format media yang didukung</a> untuk mengetahui kontainer yang didukung untuk format/codec yang ada.<br/><br/>
    <i><font color="#F38596">Terima kasih telah menggunakan Music Player GO ♥</font></i>
  ]]>
</string>
```

**Comment by enricocid** [comment]
Thanks :)

**Comment by enricocid** [comment]
Hello, 

Sorry for disturb but there are few new strings. These are the last, then I'll release 4.0.0, hopefully during the weekend. Thanks :)

```
<string name="reset_library_title">Music library</string>
<string name="reset_library_summary">Found songs: %1d</string>
<string name="reset_library_message">Songs library will be reset and app restarted. Continue?</string>
```

**Comment by zmni** [comment]
```xml
<string name="reset_library_title">Pustaka musik</string>
<string name="reset_library_summary">Lagu yang ditemukan: %1d</string>
<string name="reset_library_message">Pustaka musik akan disetel ulang dan aplikasi akan dimulai ulang. Lanjutkan?</string>
```

**Pull request closed without merging**
