### PR TITLE
Updating Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by 7glaucio**

### CODE REVIEW

**Comment by enricocid** [comment]
Thanks! :)

**Comment by enricocid** [comment]
Hi, ptbr is not recognized as region code. The correct code is [pt-rBR](https://github.com/enricocid/Music-Player-GO/commit/d64903c2b5cf00b73f4074d993a6d38e1fcadd72) :)

**Comment by 7glaucio** [comment]
@enricocid Sorry, I didn't know that. Did you change it already?

**Comment by enricocid** [comment]
@7glaucio No problem :) thanks again for contributing :)

**Pull request merged**
