### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by NathanBnm**
I updated the French translation.
However I have a few questions before merging, that's why I am marking this as draft.

Is `&#160` used to create an unbreakable space?

I didn't find a proper way to translate this into French:
```xml
    <string name="sorting_pref_ascending">Ascending</string>
    <string name="sorting_pref_descending">Descending</string>
```
What do you think about this?
```xml
    <string name="sorting_pref_ascending">A-Z</string>
    <string name="sorting_pref_descending">Z-A</string>
```
Maybe it's better as a source too.

And for now I don't know what is the context of this string and I don't know how to translate it:
```xml
    <string name="edge_pref_summary_on">Disable edge-to-edge</string>
    <string name="edge_pref_summary_off">Enable edge-to-edge</string>
```
Could you please answer my questions. Then I'll do the appropriate edits before making this PR ready :smile: Thanks in advance.

### CODE REVIEW

**Comment by enricocid** [comment]
1. About edge-to-edge: just translate disable and enable as this is an android feature
2. I'm ok with the sorting proposal :)

**Comment by NathanBnm** [comment]
Thanks for your reply! You just missed that one :wink: 

> Is `&#160` used to create an unbreakable space?
> 

I'm going to update the source string too if you want when I have time.

**Comment by enricocid** [comment]
> 
> > Is `&#160` used to create an unbreakable space?
> 

yes. 
Thanks :)

**Comment by NathanBnm** [comment]
Ready to go! :smile:

**Comment by enricocid** [comment]
Thanks! :)

**Pull request merged**
