### PR TITLE
Feature/sleeptimer

### PR DESCRIPTION
**Pull request by watauoa**
Hello, it's the first time to pull-request you! I'm Wataru.
I tried to implement the simple sleep timer because it was mentioned in #300.
Is it helpful? Any idea for improvement is welcome!

### CODE REVIEW

**Comment by enricocid** [comment]
Thanks! Highly appreciated! :)
Gonna check it asap!

**Comment by watauoa** [comment]
Additionally, I was added the UI for a more detailed time setting.

**Comment by enricocid** [comment]
Hi, build failed 😊

**Comment by enricocid** [comment]
Hi, build failed 😊

IMG_20220325_095503

**Comment by watauoa** [comment]
sorry🙇, check asap.

**Comment by enricocid** [comment]
👍🏻😊

**Comment by watauoa** [comment]
Fixed. Can this pass the build test?

**Comment by enricocid** [comment]
Hi, thanks for your submission.
Anyway I don't think the design fits with the app which is simpler.

I prefer the previous implementation, i.e. a list of presets :)

Waiting for a new PR to work on...

PS sorry for late reply but atm I don't have much time to dedicate on this project. :)

**Comment by watauoa** [comment]
Thanks for your feedback. I will revert to the presets version.

**Comment by watauoa** [comment]
Reverted.

**Comment by enricocid** [comment]
Thanks, gonna merge tomorrow :)

**Pull request merged**
