### PR TITLE
Play album on title click

### PR DESCRIPTION
**Pull request by Drhaal**
Clicking on the title of the currently selected album title now plays the first song of this album (in fact the click is set on the selected album container to be coherent with the present of a ripple animation)

This allow to start playing an album while browsing it's songs without having to scroll up to the top

Here's the debug APK: https://send.firefox.com/download/508f78e583fc19ee/#kq86VUiAmC3OpTtzXmLRYw

### CODE REVIEW

**Comment by enricocid** [comment]
For some reason this is not working as expected. 
When I select the album and then I navigate to another, I'm not able to check the previously selected album

**Comment by Drhaal** [comment]
Didn't noticed this,
I will try to test it next week-end.

**Comment by enricocid** [comment]
Thanks, if you want you can remove recyclical implementation to setupnthe RV and use the native one ... 😉

**Comment by enricocid** [comment]
What if you just add the else branch in the onClick method, i.e. when the album is already selected scroll to top and play the first song. Can't try now, let me know if you can

**Comment by Drhaal** [comment]
I will try it this weekend

**Comment by Drhaal** [comment]
I re-added the option to click on the album title to focus it. It was accidentally overwritten. I put it on long press with the short press playing the first song of the album. 

I haven't encountered any bug with the code have you encountered it again ?

**Comment by enricocid** [comment]
[Added](https://github.com/enricocid/Music-Player-GO/commit/84bcf32822e2795770eb2fa9e9a5a411c0047131)

As said earlier, there was a simpler method to implement this feature so I decided to go with it :)

**Pull request closed without merging**
