### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR removes the links to Izzy repos, since your app is now part from the official repo ;)

### CODE REVIEW

**Comment by enricocid** [comment]
merged, thanks :D

**Comment by rozari0** [comment]
> Hi,
> 
> This small PR removes the links to Izzy repos, since your app is now part from the official repo ;)

Official repo is too slow, also this app hasn't been updated for a while in the official repo. It should also be in @IzzySoft's repo repo.

**Comment by IzzySoft** [comment]
Can be re-established any time if @enricocid wants it to. But for double-listing I'd prefer him to confirm he's OK with that. You know that cross-updates won't work, though, @rozari0? You'd need to uninstall and re-install if you want to switch then, as the signatures of the APKs from F-Droid won't match those of the APKs signed by Enrico.

**Comment by rozari0** [comment]
> Though, @rozari0? You'd need to uninstall and re-install if you want to switch then, as the signatures of the APKs from F-Droid won't match those of the APKs signed by Enrico.

Yes, I know. : )
I'm already using from GH release, so I don't think I have to reinstall.

**Comment by IzzySoft** [comment]
No, in that case then definitely not, same source :smile:

**Pull request merged**
